df<-read.table("household_power_consumption.txt",header=T, sep=";")
df$Date<-as.Date(df$Date,"%d/%m/%Y")
sdf<-subset(df, Date=='2007-02-01')
sdf2<-subset(df, Date=='2007-02-02')
sdf3<-rbind(sdf,sdf2)
h<-sdf3$Global_active_power
h<-gsub("?","",h)
h<-as.numeric(h)
d<-paste(sdf3$Date,sdf3$Time)
x<-as.POSIXct(d)
png(filename='plot2.png', width = 480, height = 480, units='px')
plot(x,h, type='n',xlab='', ylab='Global active power (kilowatts)')
lines(x,h)
dev.off()